[package]
name = "northstar-discord-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrplug = { git = "https://github.com/catornot/rrplug.git", features=["presence"] }
# rrplug = { path = "../rrplug", features=["full"] }
discord-sdk = "0.3.2"
tokio = "1.26.0"

[build-dependencies]
windres = "0.2.2"

[lib]
# name = "DiscordRPCV" # not if we really need this also ignore non snake case should be added to lib.rs then
crate-type = ["cdylib"]
